# Generated by Django 6.0.2 on 2026-03-10 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltepesiapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='HarvesterActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('HARVESTING', 'Harvesting'), ('PINCHING', 'Pinching'), ('PLANTING', 'Planting'), ('GREENHOUSE_PREP', 'Greenhouse Preparations'), ('STAPLING_BOXES', 'Stapling Boxes'), ('COLDSTORE', 'Coldstore'), ('WASTE_COLLECTION', 'Waste Collection')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltepesiapp.group')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltepesiapp.teamleader')),
            ],
        ),
    ]
